#!/usr/bin/env sh

# Set environment variables
STACK_NAME=${STACK_NAME:-checkout}
STACK_ENV=${STACK_ENV:-dev}
STACK=${STACK_NAME}-${STACK_ENV}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-eu-west-3}

# Remove serverless stack
sls remove \
  --service ${STACK_NAME} \
  --stage ${STACK_ENV} \
  --region ${AWS_DEFAULT_REGION}
