USER_ID = 'The user’s unique ID.'
USER_FIRST_NAME = 'The user’s first name.'
USER_LAST_NAME = 'The user’s last name.'
USER_EMAIL = 'The user’s email address.'
USER_PASSWORD = 'The user’s password.'
USER_PHONE = 'The user’s phone number.'
USER_AUTHENTICATION_PAYLOAD_TOKEN = 'Token used for user authentication.'
USER_DEFAULT_ADDRESS = 'The user’s default address.'
USER_RESET_TOKEN = 'The reset token required to reset the user’s password.'
USER_NEW_PASSWORD = 'The user’s new password.'
USER_MERCHANT_ID = 'The ID of the merchant this user belongs to.'
USER_CREATE_INPUT = 'The properties used to create a user.'
USER_UPDATE_INPUT = 'The properties used to update a user.'
USER_RESET_INPUT = 'The properties used to reset a user’s password.'

AUTHENTICATION_PAYLOAD_TOKEN = 'Token used for authentication.'
