version: "3"

services:
  app:
    build: .
    volumes: [".:/usr/src/app:delegated"]
    ports: ["5005:5000"]
    env_file: [".env"]
    environment:
      FLASK_APP: src.server
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 0
      PIPENV_DONT_LOAD_ENV: 1
    command: ["python", "-u", "-m", "flask", "run", "--host", "0.0.0.0"]
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes: [
      "db:/var/lib/mysql:delegated",
      "./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh"
    ]
    ports: ["9091:${DB_PORT}"]
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: y
      TZ: Europe/Amsterdam
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    

volumes:
  db: {}
